### ISSUE TITLE
use SafeMath

### ISSUE THREAD

**Issue by SCBuergel** [dexDev/DEx.top#6]
I suggest you use the common [SafeMath library](https://openzeppelin.org/api/docs/math_SafeMath.html) to prevent overflows instead of writing some checks yourself (like [here](https://github.com/dexDev/DEx.top/blob/master/smart-contract/dextop.sol#L413)).

**Comment by libreoscar** [comment]
Thanks for the suggestion. Since we are using non-256-bit integers heavily for gas cost saving, the SafeMath library does not fit our model well. We perform overflow checking extensively, and in many cases the possibility of overflow can be eliminated by storing intermediate result with a wider integer type, e.g. storing `uint64(a) * uint64(b)` into a `uint256`. We believe our choices lead to overall better readability and efficiency than SafeMath style expressions, though taking extra carefulness.
